# Generated by Django 5.2.10 on 2026-02-08 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataticket',
            name='building',
            field=models.CharField(blank=True, help_text='e.g., Building A', max_length=100),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='floor',
            field=models.CharField(blank=True, help_text='e.g., 4th Floor', max_length=20),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for searching'),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_ticket', to='chatbot.location'),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='room_description',
            field=models.TextField(blank=True, help_text='Description of the room'),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='room_name',
            field=models.CharField(blank=True, help_text='Descriptive name', max_length=200),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='room_number',
            field=models.CharField(blank=True, help_text='e.g., 401, Smart Lab', max_length=50),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='ticket_type',
            field=models.CharField(choices=[('training_data', 'Training Data'), ('location', 'Location/Room')], default='training_data', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataticket',
            name='answer',
            field=models.TextField(blank=True, help_text='Bot response'),
        ),
        migrations.AlterField(
            model_name='dataticket',
            name='question',
            field=models.TextField(blank=True, help_text='Sample question/user input'),
        ),
    ]
