# Generated by Django 5.2.10 on 2026-02-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_locationticket_locationticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataticket',
            name='target_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_requests', to='chatbot.trainingdata'),
        ),
        migrations.AddField(
            model_name='dataticket',
            name='ticket_type',
            field=models.CharField(choices=[('create', 'Create New'), ('update', 'Update Existing')], default='create', max_length=10),
        ),
    ]
