# Generated by Django 5.2.10 on 2026-02-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_dataticket_target_training_dataticket_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataticket',
            name='target_training',
        ),
        migrations.RemoveField(
            model_name='dataticket',
            name='ticket_type',
        ),
    ]
