# Generated by Django 5.2.10 on 2026-02-18 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_remove_dataticket_target_training_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingUpdateTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('new_questions', models.TextField(help_text='Proposed additional questions')),
                ('new_answer', models.TextField(blank=True, help_text='Proposed updated answer')),
                ('reason', models.TextField(help_text='Why this update is needed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.office')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_update_tickets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_update_tickets', to=settings.AUTH_USER_MODEL)),
                ('training_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_tickets', to='chatbot.trainingdata')),
            ],
        ),
    ]
