# Generated by Django 5.2.10 on 2026-02-20 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_trainingupdateticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingdata',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='trainingdata',
            name='questions',
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Has admin reviewed this?'),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='notes',
            field=models.TextField(blank=True, help_text='Submission notes from staff'),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_data', to='chatbot.office'),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='questions_data',
            field=models.JSONField(default=list, help_text='List of sample questions'),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_training_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_training_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='answer',
            field=models.TextField(help_text='Bot response for this intent'),
        ),
    ]
