# Generated by Django 5.2.10 on 2026-02-25 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_category_intent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
