# Generated by Django 5.2.10 on 2026-03-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_alter_chatlog_predicted_intent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketcomment',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='locationticket',
            name='location',
        ),
        migrations.RemoveField(
            model_name='locationticket',
            name='office',
        ),
        migrations.RemoveField(
            model_name='locationticket',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='locationticket',
            name='submitted_by',
        ),
        migrations.RemoveField(
            model_name='locationticketcomment',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='locationticketcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='user',
        ),
        migrations.DeleteModel(
            name='DataTicket',
        ),
        migrations.DeleteModel(
            name='LocationTicket',
        ),
        migrations.DeleteModel(
            name='LocationTicketComment',
        ),
        migrations.DeleteModel(
            name='TicketComment',
        ),
    ]
