# Generated by Django 5.2.10 on 2026-02-03 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_intentresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdata',
            name='question',
        ),
        migrations.AddField(
            model_name='trainingdata',
            name='questions',
            field=models.TextField(default='[]', help_text='JSON array of question variations'),
        ),
        migrations.AlterField(
            model_name='trainingdata',
            name='intent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_samples', to='chatbot.intent'),
        ),
    ]
