# Generated by Django 5.2.10 on 2026-02-07 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_remove_trainingdata_question_trainingdata_questions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(help_text='e.g., 401, 402, Smart Lab', max_length=50, unique=True)),
                ('room_name', models.CharField(blank=True, help_text='e.g., Smart Lab, Computer Lab', max_length=200)),
                ('building', models.CharField(help_text='e.g., Building A, Main Building', max_length=100)),
                ('floor', models.CharField(help_text='e.g., 4th Floor, Ground Floor', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description of the room')),
                ('aliases', models.TextField(blank=True, help_text='JSON list of alternative names')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['building', 'floor', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='LocationKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(help_text="e.g., '401', 'smart lab', 'smartlab'", max_length=100)),
                ('priority', models.IntegerField(default=1, help_text='Higher = more important')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='chatbot.location')),
            ],
            options={
                'unique_together': {('location', 'keyword')},
            },
        ),
    ]
