# Generated by Django 5.2.10 on 2026-02-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_dataticket_building_dataticket_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataticket',
            name='building',
        ),
        migrations.RemoveField(
            model_name='dataticket',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='dataticket',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='dataticket',
            name='location',
        ),
        migrations.RemoveField(
            model_name='dataticket',
            name='room_description',
        ),
        migrations.RemoveField(
            model_name='dataticket',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='dataticket',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='dataticket',
            name='ticket_type',
        ),
        migrations.AlterField(
            model_name='dataticket',
            name='answer',
            field=models.TextField(help_text='Bot response'),
        ),
        migrations.AlterField(
            model_name='dataticket',
            name='question',
            field=models.TextField(help_text='Sample question/user input'),
        ),
    ]
