# Generated by Django 5.2.10 on 2026-02-08 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_remove_dataticket_building_remove_dataticket_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('room_number', models.CharField(help_text='e.g., 401, Smart Lab', max_length=50)),
                ('room_name', models.CharField(blank=True, help_text='Descriptive name (optional)', max_length=200)),
                ('building', models.CharField(help_text='e.g., Building A', max_length=100)),
                ('floor', models.CharField(help_text='e.g., 4th Floor', max_length=20)),
                ('room_description', models.TextField(blank=True, help_text='Description of the room')),
                ('keywords', models.TextField(help_text='Comma-separated keywords for searching')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional context or notes')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin feedback')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_ticket', to='chatbot.location')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_tickets', to='chatbot.office')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_location_tickets', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_location_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Ticket',
                'verbose_name_plural': 'Location Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationTicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='chatbot.locationticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Ticket Comment',
                'verbose_name_plural': 'Location Ticket Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
