# Generated by Django 5.2.10 on 2026-02-25 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_alter_trainingdata_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name (e.g., Enrollment, Scholarships)', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version', max_length=100, unique=True)),
                ('icon', models.CharField(default='❓', help_text='Emoji icon for the category', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='intent',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category for menu organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intents', to='chatbot.category'),
        ),
    ]
