# Generated by Django 5.2.10 on 2026-03-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_remove_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='predicted_intent',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='dataticket',
            name='new_intent_name',
            field=models.CharField(blank=True, help_text='If creating new intent', max_length=150),
        ),
        migrations.AlterField(
            model_name='dataticket',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='intent',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.CharField(help_text='e.g., Building A, Main Building', max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='floor',
            field=models.CharField(help_text='e.g., 4th Floor, Ground Floor', max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_name',
            field=models.CharField(blank=True, help_text='e.g., Smart Lab, Computer Lab', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='room_number',
            field=models.CharField(help_text='e.g., 401, 402, Smart Lab', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='locationkeyword',
            name='keyword',
            field=models.CharField(help_text="e.g., '401', 'smart lab', 'smartlab'", max_length=200),
        ),
        migrations.AlterField(
            model_name='locationticket',
            name='building',
            field=models.CharField(help_text='e.g., Building A', max_length=200),
        ),
        migrations.AlterField(
            model_name='locationticket',
            name='floor',
            field=models.CharField(help_text='e.g., 4th Floor', max_length=50),
        ),
        migrations.AlterField(
            model_name='locationticket',
            name='room_name',
            field=models.CharField(blank=True, help_text='Descriptive name (optional)', max_length=255),
        ),
        migrations.AlterField(
            model_name='locationticket',
            name='room_number',
            field=models.CharField(help_text='e.g., 401, Smart Lab', max_length=200),
        ),
        migrations.AlterField(
            model_name='locationticket',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='modelversion',
            name='version',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='trainingupdateticket',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=40, unique=True),
        ),
    ]
